import { renderSidebar } from './components/sidebar.js';

renderSidebar(document.querySelector('#dashboard-sidebar'));
const list=document.querySelector('[data-coupons-list]');const dialog=document.querySelector('[data-coupon-dialog]');const form=document.querySelector('[data-coupon-form]');const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));let coupons=[];
async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});if(response.status===401)return location.replace('/?auth=expired');if(response.status===204)return null;const body=await response.json();if(!response.ok)throw new Error(body.error||'Não foi possível concluir.');return body;}
async function loadUser(){const context=await api('/api/auth/me');const name=context.user.name;document.querySelector('.user strong').textContent=name;document.querySelector('.user > span').textContent=name.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase();const shop=context.memberships[0]?.barbershops?.name;if(shop){document.querySelector('.shop-card strong').textContent=shop;document.querySelector('.shop-card > span').textContent=shop.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase();}}
const formatDate=value=>value?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value)):'';
function render(){document.querySelector('[data-active-coupons]').textContent=coupons.filter(c=>c.active).length;document.querySelector('[data-total-uses]').textContent=coupons.reduce((sum,c)=>sum+c.uses_count,0);if(!coupons.length)return void(list.innerHTML='<div class="coupons-empty">Nenhum cupom criado. Crie o primeiro para divulgar aos seus clientes.</div>');list.innerHTML=coupons.map(c=>{const discount=c.discount_type==='percent'?`${c.discount_value}% OFF`:`${money.format(c.discount_value/100)} OFF`;const limit=c.max_uses||null;const usage=limit?Math.min(100,Math.round(c.uses_count/limit*100)):0;const validity=c.ends_at?`Válido até ${formatDate(c.ends_at)}`:'Sem data de expiração';return `<article class="coupon-card ${c.active?'':'inactive'}"><div class="coupon-card-top"><span class="coupon-code">${escapeHtml(c.code)}</span><span class="coupon-state ${c.active?'':'off'}">${c.active?'ATIVO':'PAUSADO'}</span></div><strong class="coupon-discount">${discount}</strong><span class="coupon-description">${validity}${c.min_order_cents?` · Pedido mínimo ${money.format(c.min_order_cents/100)}`:''}</span><div class="coupon-progress"><div class="coupon-progress-head"><span>${c.uses_count} ${c.uses_count===1?'uso':'usos'}</span><span>${limit?`limite ${limit}`:'sem limite'}</span></div><div class="coupon-progress-track"><i style="width:${usage}%"></i></div></div><div class="coupon-actions"><button data-edit="${c.id}">Editar</button><button data-toggle="${c.id}">${c.active?'Pausar':'Ativar'}</button><button class="delete" data-delete="${c.id}">Excluir</button></div></article>`}).join('');}
async function loadCoupons(){list.innerHTML='<div class="coupons-empty">Carregando cupons...</div>';try{coupons=await api('/api/schedule/coupons');render();}catch(error){list.innerHTML=`<div class="coupons-empty">${escapeHtml(error.message)}</div>`;}}
function localDate(value){if(!value)return'';const date=new Date(value);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16);}
function openForm(coupon){form.reset();form.elements.id.value=coupon?.id||'';form.elements.code.value=coupon?.code||'';form.elements.discountType.value=coupon?.discount_type||'percent';form.elements.discountValue.value=coupon?(coupon.discount_type==='fixed'?coupon.discount_value/100:coupon.discount_value):10;form.elements.minimumOrder.value=coupon?coupon.min_order_cents/100:0;form.elements.maxUses.value=coupon?.max_uses||'';form.elements.startsAt.value=localDate(coupon?.starts_at);form.elements.endsAt.value=localDate(coupon?.ends_at);document.querySelector('[data-coupon-eyebrow]').textContent=coupon?'EDITAR CUPOM':'NOVO CUPOM';document.querySelector('[data-coupon-title]').textContent=coupon?'Atualizar cupom':'Criar cupom';dialog.showModal();}
document.querySelector('[data-new-coupon]').addEventListener('click',()=>openForm());document.querySelectorAll('[data-coupon-close]').forEach(button=>button.addEventListener('click',()=>dialog.close()));form.elements.code.addEventListener('input',event=>event.target.value=event.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,''));
list.addEventListener('click',async event=>{const edit=event.target.closest('[data-edit]');if(edit)return openForm(coupons.find(c=>c.id===edit.dataset.edit));const toggle=event.target.closest('[data-toggle]');if(toggle){const coupon=coupons.find(c=>c.id===toggle.dataset.toggle);toggle.disabled=true;try{const saved=await api(`/api/schedule/coupons/${coupon.id}`,{method:'PATCH',body:JSON.stringify({active:!coupon.active})});coupons=coupons.map(c=>c.id===saved.id?saved:c);render();}catch(error){alert(error.message);}return;}const remove=event.target.closest('[data-delete]');if(!remove||!confirm('Excluir este cupom?'))return;try{await api(`/api/schedule/coupons/${remove.dataset.delete}`,{method:'DELETE'});coupons=coupons.filter(c=>c.id!==remove.dataset.delete);render();}catch(error){alert(error.message);}});
form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('[type="submit"]');const error=document.querySelector('[data-coupon-error]');const label=button.textContent;button.disabled=true;button.textContent='Salvando...';error.textContent='';try{const payload=Object.fromEntries(new FormData(form));const id=payload.id;delete payload.id;const saved=await api(id?`/api/schedule/coupons/${id}`:'/api/schedule/coupons',{method:id?'PATCH':'POST',body:JSON.stringify(payload)});coupons=id?coupons.map(c=>c.id===saved.id?saved:c):[saved,...coupons];render();dialog.close();}catch(failure){error.textContent=failure.message;}finally{button.disabled=false;button.textContent=label;}});
document.querySelector('[data-sidebar-open]').addEventListener('click',()=>document.body.classList.add('sidebar-open'));document.querySelectorAll('[data-sidebar-close]').forEach(button=>button.addEventListener('click',()=>document.body.classList.remove('sidebar-open')));document.querySelector('[data-logout]').addEventListener('click',async event=>{event.preventDefault();await api('/api/auth/logout',{method:'POST'});location.replace('/');});Promise.all([loadUser(),loadCoupons()]);
