import { renderSidebar } from './components/sidebar.js';

renderSidebar(document.querySelector('#dashboard-sidebar'));
const list=document.querySelector('[data-professionals-list]');const dialog=document.querySelector('[data-professional-dialog]');const form=document.querySelector('[data-professional-form]');const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));let professionals=[];
async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});if(response.status===401)return location.replace('/?auth=expired');const body=await response.json();if(!response.ok)throw new Error(body.error||'Não foi possível concluir.');return body;}
async function loadUser(){const context=await api('/api/auth/me');const name=context.user.name;document.querySelector('.user strong').textContent=name;document.querySelector('.user > span').textContent=name.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase();const shop=context.memberships[0]?.barbershops?.name;if(shop){document.querySelector('.shop-card strong').textContent=shop;document.querySelector('.shop-card > span').textContent=shop.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase();}}
function render(){const today=new Date().toISOString().slice(0,10);document.querySelector('[data-professionals-active]').textContent=professionals.filter(item=>item.active).length;document.querySelector('[data-professionals-today]').textContent=professionals.reduce((sum,item)=>sum+item.appointments.filter(a=>a.starts_at.slice(0,10)===today&&a.status!=='cancelled').length,0);if(!professionals.length)return void(list.innerHTML='<div class="professionals-empty">Nenhum profissional cadastrado.</div>');list.innerHTML=professionals.map(item=>{const initials=item.name.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase();const activeAppointments=item.appointments.filter(a=>a.status!=='cancelled');return `<article class="professional-row"><div class="professional-profile"><span class="professional-avatar">${escapeHtml(initials)}</span><div><strong>${escapeHtml(item.name)}</strong><small>${item.active?'Disponível para receber horários':'Fora da agenda'}</small></div></div><div class="professional-stat"><strong>${activeAppointments.length}</strong><small>atendimentos</small></div><span class="professional-status ${item.active?'':'off'}">${item.active?'Ativo':'Pausado'}</span><div class="professional-actions"><button data-edit="${item.id}">Editar</button><button data-toggle="${item.id}">${item.active?'Pausar':'Ativar'}</button></div></article>`}).join('');}
async function loadProfessionals(){list.innerHTML='<div class="professionals-empty">Carregando...</div>';try{professionals=await api('/api/schedule/professionals');render();}catch(error){list.innerHTML=`<div class="professionals-empty">${escapeHtml(error.message)}</div>`;}}
function openForm(item){form.reset();form.elements.id.value=item?.id||'';form.elements.name.value=item?.name||'';document.querySelector('[data-professional-eyebrow]').textContent=item?'EDITAR PROFISSIONAL':'NOVO PROFISSIONAL';document.querySelector('[data-professional-title]').textContent=item?'Atualizar profissional':'Adicionar à equipe';dialog.showModal();}
document.querySelector('[data-new-professional]').addEventListener('click',()=>openForm());document.querySelectorAll('[data-professional-close]').forEach(button=>button.addEventListener('click',()=>dialog.close()));list.addEventListener('click',async event=>{const edit=event.target.closest('[data-edit]');if(edit)return openForm(professionals.find(item=>item.id===edit.dataset.edit));const toggle=event.target.closest('[data-toggle]');if(!toggle)return;const item=professionals.find(p=>p.id===toggle.dataset.toggle);toggle.disabled=true;toggle.textContent='Salvando...';try{const updated=await api(`/api/schedule/professionals/${item.id}`,{method:'PATCH',body:JSON.stringify({active:!item.active})});professionals=professionals.map(p=>p.id===updated.id?{...p,...updated}:p);render();}catch(error){alert(error.message);toggle.disabled=false;}});
form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('[type="submit"]');const error=document.querySelector('[data-professional-error]');const label=button.textContent;button.disabled=true;button.textContent='Salvando...';error.textContent='';try{const payload=Object.fromEntries(new FormData(form));const id=payload.id;delete payload.id;const saved=await api(id?`/api/schedule/professionals/${id}`:'/api/schedule/professionals',{method:id?'PATCH':'POST',body:JSON.stringify(payload)});professionals=id?professionals.map(p=>p.id===saved.id?{...p,...saved}:p):[...professionals,saved];render();dialog.close();}catch(failure){error.textContent=failure.message;}finally{button.disabled=false;button.textContent=label;}});
document.querySelector('[data-sidebar-open]').addEventListener('click',()=>document.body.classList.add('sidebar-open'));document.querySelectorAll('[data-sidebar-close]').forEach(button=>button.addEventListener('click',()=>document.body.classList.remove('sidebar-open')));document.querySelector('[data-logout]').addEventListener('click',async event=>{event.preventDefault();await api('/api/auth/logout',{method:'POST'});location.replace('/');});Promise.all([loadUser(),loadProfessionals()]);
