import { renderSidebar } from './components/sidebar.js';
import { icon } from './components/icons.js';

renderSidebar(document.querySelector('#dashboard-sidebar'));
const list = document.querySelector('[data-services-list]');
const dialog = document.querySelector('[data-service-dialog]');
const form = document.querySelector('[data-service-form]');
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
let services = [];

async function api(path, options = {}) { const response = await fetch(path, { credentials: 'same-origin', ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); if (response.status === 401) return location.replace('/?auth=expired'); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível concluir.'); return body; }
async function loadUser() { const context = await api('/api/auth/me'); const name = context.user.name; document.querySelector('.user strong').textContent = name; document.querySelector('.user > span').textContent = name.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase(); const shop=context.memberships[0]?.barbershops?.name; if(shop){document.querySelector('.shop-card strong').textContent=shop;document.querySelector('.shop-card > span').textContent=shop.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase();} }

function render() {
  const active = services.filter(service => service.active);
  document.querySelector('[data-active-services]').textContent = active.length;
  document.querySelector('[data-average-price]').textContent = money.format(active.length ? active.reduce((sum, item) => sum + item.price_cents, 0) / active.length / 100 : 0);
  if (!services.length) return void (list.innerHTML = '<div class="services-empty">Nenhum serviço cadastrado.</div>');
  list.innerHTML = services.map(service => `<article class="service-row"><div class="service-name"><span class="service-icon">${icon('scissors')}</span><div><strong>${escapeHtml(service.name)}</strong><small>${service.active ? 'Disponível para agendamento' : 'Pausado'}</small></div></div><div class="service-meta"><strong>${service.duration_minutes} min</strong><small>duração</small></div><div class="service-meta"><strong>${money.format(service.price_cents / 100)}</strong><small>preço</small></div><span class="service-state ${service.active ? '' : 'off'}">${service.active ? 'Ativo' : 'Pausado'}</span><div class="service-actions"><button data-edit="${service.id}">Editar</button><button data-toggle="${service.id}">${service.active ? 'Pausar' : 'Ativar'}</button></div></article>`).join('');
}
async function loadServices(){list.innerHTML='<div class="services-empty">Carregando...</div>';try{services=await api('/api/schedule/services');render();}catch(error){list.innerHTML=`<div class="services-empty">${escapeHtml(error.message)}</div>`;}}
function openForm(service){form.reset();form.elements.id.value=service?.id||'';form.elements.name.value=service?.name||'';form.elements.duration.value=service?.duration_minutes||30;form.elements.price.value=service?(service.price_cents/100).toFixed(2):'0';document.querySelector('[data-service-eyebrow]').textContent=service?'EDITAR SERVIÇO':'NOVO SERVIÇO';document.querySelector('[data-service-title]').textContent=service?'Atualizar serviço':'Adicionar serviço';dialog.showModal();}
document.querySelector('[data-new-service]').addEventListener('click',()=>openForm());document.querySelectorAll('[data-service-close]').forEach(button=>button.addEventListener('click',()=>dialog.close()));
list.addEventListener('click',async event=>{const edit=event.target.closest('[data-edit]');if(edit)return openForm(services.find(item=>item.id===edit.dataset.edit));const toggle=event.target.closest('[data-toggle]');if(!toggle)return;const service=services.find(item=>item.id===toggle.dataset.toggle);toggle.disabled=true;toggle.textContent='Salvando...';try{const updated=await api(`/api/schedule/services/${service.id}`,{method:'PATCH',body:JSON.stringify({active:!service.active})});services=services.map(item=>item.id===updated.id?updated:item);render();}catch(error){alert(error.message);toggle.disabled=false;}});
form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('[type="submit"]');const error=document.querySelector('[data-service-error]');const label=button.textContent;button.disabled=true;button.textContent='Salvando...';error.textContent='';try{const payload=Object.fromEntries(new FormData(form));const id=payload.id;delete payload.id;const saved=await api(id?`/api/schedule/services/${id}`:'/api/schedule/services',{method:id?'PATCH':'POST',body:JSON.stringify(payload)});services=id?services.map(item=>item.id===saved.id?saved:item):[...services,saved];render();dialog.close();}catch(failure){error.textContent=failure.message;}finally{button.disabled=false;button.textContent=label;}});
document.querySelector('[data-sidebar-open]').addEventListener('click',()=>document.body.classList.add('sidebar-open'));document.querySelectorAll('[data-sidebar-close]').forEach(button=>button.addEventListener('click',()=>document.body.classList.remove('sidebar-open')));document.querySelector('[data-logout]').addEventListener('click',async event=>{event.preventDefault();await api('/api/auth/logout',{method:'POST'});location.replace('/');});Promise.all([loadUser(),loadServices()]);
